# test_config.yaml
stages:
- name: tests_lora
  steps:
    - name: test_llama_lora
      flavor: g2
      command: PT_HPU_LAZY_MODE=1 VLLM_SKIP_WARMUP=true pytest -v tests/lora/test_llama_hpu.py::test_llama_lora_1x
    - name: test_multilora
      flavor: g2
      command: PT_HPU_LAZY_MODE=1 VLLM_SKIP_WARMUP=true pytest -v tests/lora/test_multilora_hpu.py::test_llama_multilora_1x
    - name: test_long_context
      flavor: g2
      command: cp /software/users/hkhier/latest_master_next/libTPCFuser.so /usr/lib/habanalabs/ && FUSER_ENABLE_MULF_ACC=true PT_HPU_LAZY_MODE=1 VLLM_SKIP_WARMUP=true pytest -v tests/lora/test_long_context_hpu.py::test_quality

    
